/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#6d5100",
        "tertiary-fixed": "#a5eeff",
        "on-primary": "#3f2e00",
        "secondary-fixed-dim": "#ffb3ac",
        "surface-container-high": "#2a2a2b",
        primary: "#ffe4af",
        secondary: "#ffb3ac",
        "on-surface": "#e5e2e3",
        "on-primary-fixed": "#261a00",
        error: "#ffb4ab",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#001f25",
        "surface-container-lowest": "#0e0e0f",
        "inverse-primary": "#785900",
        "surface-tint": "#fabd00",
        "error-container": "#93000a",
        "on-surface-variant": "#d4c5ab",
        "on-secondary-fixed-variant": "#930010",
        "secondary-container": "#a40213",
        "primary-fixed": "#ffdf9e",
        "outline-variant": "#4f4632",
        background: "#131314",
        "on-secondary-fixed": "#410003",
        "on-tertiary-container": "#005e6c",
        "on-error": "#690005",
        tertiary: "#b4f0ff",
        "on-primary-fixed-variant": "#5b4300",
        "surface-container-highest": "#353436",
        "inverse-on-surface": "#313031",
        outline: "#9c8f78",
        "surface-container": "#201f20",
        "secondary-fixed": "#ffdad6",
        "primary-container": "#ffc107",
        surface: "#131314",
        "on-background": "#e5e2e3",
        "tertiary-fixed-dim": "#00daf8",
        "tertiary-container": "#00defd",
        "on-tertiary-fixed-variant": "#004e5a",
        "on-secondary": "#680008",
        "surface-dim": "#131314",
        "surface-container-low": "#1c1b1c",
        "primary-fixed-dim": "#fabd00",
        "surface-bright": "#3a393a",
        "inverse-surface": "#e5e2e3",
        "on-secondary-container": "#ffaea6",
        "surface-variant": "#353436",
        "on-tertiary": "#00363f",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
