export const LANGUAGE_NAMES: Record<string, string> = {
  en: "English",
  fr: "French",
  es: "Spanish",
  de: "German",
  it: "Italian",
  ja: "Japanese",
  ko: "Korean",
  zh: "Chinese",
  pt: "Portuguese",
  ru: "Russian",
  hi: "Hindi",
  ar: "Arabic",
  sv: "Swedish",
  da: "Danish",
  nl: "Dutch",
  pl: "Polish",
  th: "Thai",
  tr: "Turkish",
  cs: "Czech",
  no: "Norwegian",
  fi: "Finnish",
  hu: "Hungarian",
  el: "Greek",
  he: "Hebrew",
  ro: "Romanian",
  id: "Indonesian",
  ms: "Malay",
  vi: "Vietnamese",
  tl: "Filipino",
  uk: "Ukrainian",
  fa: "Persian",
  bn: "Bengali",
  ta: "Tamil",
  te: "Telugu",
  ml: "Malayalam",
  cn: "Cantonese",
  la: "Latin",
  sr: "Serbian",
  hr: "Croatian",
  bg: "Bulgarian",
  sk: "Slovak",
  lt: "Lithuanian",
  lv: "Latvian",
  et: "Estonian",
  sl: "Slovenian",
  is: "Icelandic",
  ga: "Irish",
  ka: "Georgian",
  sq: "Albanian",
  mk: "Macedonian",
  bs: "Bosnian",
  af: "Afrikaans",
  sw: "Swahili",
  ur: "Urdu",
  ne: "Nepali",
  si: "Sinhala",
  km: "Khmer",
  my: "Burmese",
  lo: "Lao",
  mn: "Mongolian",
  am: "Amharic",
  hy: "Armenian",
  az: "Azerbaijani",
  kk: "Kazakh",
  uz: "Uzbek",
  tg: "Tajik",
  ky: "Kyrgyz",
  ps: "Pashto",
  ku: "Kurdish",
  gl: "Galician",
  eu: "Basque",
  ca: "Catalan",
  cy: "Welsh",
  mt: "Maltese",
  lb: "Luxembourgish",
  eo: "Esperanto",
  jv: "Javanese",
  su: "Sundanese",
  xx: "No Language",
  nb: "Norwegian Bokmal",
  nn: "Norwegian Nynorsk",
  ab: "Abkhazian",
  wo: "Wolof",
  zu: "Zulu",
  xh: "Xhosa",
  yo: "Yoruba",
  ig: "Igbo",
  ha: "Hausa",
  so: "Somali",
  rw: "Kinyarwanda",
  mg: "Malagasy",
  be: "Belarusian",
};

export function languageName(code: string): string {
  return LANGUAGE_NAMES[code] || code.toUpperCase();
}
